trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI: 'true'

steps:
# 1. Installer Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# 2. Installer Angular CLI + dépendances
- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular & dependencies'

# 3. Build Angular
- script: |
    ng build --configuration=production
  displayName: 'Build Angular App'

# 4. Lancer les tests unitaires
- script: |
    ng test --karma-config=karma.conf.js --watch=false --code-coverage --browsers=ChromeHeadless
  displayName: 'Run Unit Tests'
