trigger:
- main

pool:
  name: 'Default'  # Self-hosted agent pool

variables:
  CI: 'true'

steps:
# 1. Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# 2. Install Angular CLI globally
- script: |
    npm install -g @angular/cli
  displayName: 'Install Angular CLI'

# 3. Install project dependencies
- script: |
    npm install
  displayName: 'Install dependencies'

# 4. Build the project first (recommended before testing)
- script: |
    ng build --configuration=production
  displayName: 'Build Angular App'

# 5. Run unit tests with Karma/Jasmine
- script: |
    ng test --karma-config=karma.conf.js --watch=false --code-coverage --browsers=ChromeHeadless
  displayName: 'Run Unit Tests with Karma'

# 6. Publish test results (if you have test results in JUnit format)
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'
    searchFolder: '$(Agent.TempDirectory)'
    testRunTitle: 'Unit Tests'
  displayName: 'Publish Unit Test Results'

# 7. Publish code coverage results
- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/**/cobertura-coverage.xml'
    reportDirectory: 'coverage'
  displayName: 'Publish Code Coverage'

# 8. Install Python and Robot Framework (only if robot-tests directory exists)
- script: |
    if [ -d "robot-tests" ]; then
      echo "Robot tests directory found, installing dependencies..."
      pip install robotframework selenium robotframework-seleniumlibrary
    else
      echo "No robot-tests directory found, skipping Robot Framework installation"
    fi
  displayName: 'Install Robot Framework (conditional)'

# 9. Run Robot Framework tests (only if directory exists)
- script: |
    if [ -d "robot-tests" ]; then
      echo "Running Robot Framework tests..."
      cd robot-tests
      robot --outputdir results tests/
    else
      echo "No robot-tests directory found, skipping E2E tests"
    fi
  displayName: 'Run Robot Framework Tests (conditional)'

# 10. Publish Robot Framework test results (only if they exist)
- task: PublishTestResults@2
  condition: and(succeededOrFailed(), exists('robot-tests/results/output.xml'))
  inputs:
    testResultsFormat: 'RobotFramework'
    testResultsFiles: '**/output.xml'
    searchFolder: 'robot-tests/results'
    testRunTitle: 'Robot Framework E2E Tests'
  displayName: 'Publish Robot Test Results'